#!/bin/bash
# Installs the Koko status bar plugin into SwiftBar.
#
# SwiftBar can't simply be pointed at menubar/ in the repo: it sets the
# executable bit on every file in its plugin folder and runs them all, so it
# would try to execute README.md too. Instead this gives SwiftBar a folder of
# its own holding a one-line wrapper that runs the plugin from the repo, so
# updates to the repo take effect without reinstalling.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN="$REPO/menubar/koko.1m.sh"
PLUGIN_DIR="${SWIFTBAR_PLUGIN_DIR:-$HOME/SwiftBarPlugins}"

[ -f "$PLUGIN" ] || { echo "Can't find $PLUGIN" >&2; exit 1; }

if [ ! -d /Applications/SwiftBar.app ]; then
  echo "SwiftBar isn't installed. Get it with:"
  echo "  brew install --cask swiftbar"
  exit 1
fi

mkdir -p "$PLUGIN_DIR"
cat > "$PLUGIN_DIR/koko.1m.sh" <<WRAPPER
#!/bin/bash
# Generated by scripts/install-swiftbar.sh — edit $PLUGIN instead.
#
# runInBash=false matters: SwiftBar otherwise runs plugins through a login
# shell, which sources your profile first, and anything the profile prints to
# stdout would be shown as the status bar item instead of this plugin's output.
# <swiftbar.runInBash>false</swiftbar.runInBash>
exec "$PLUGIN" "\$@"
WRAPPER
chmod +x "$PLUGIN_DIR/koko.1m.sh"

defaults write com.ameba.SwiftBar PluginDirectory -string "$PLUGIN_DIR"

osascript -e 'quit app "SwiftBar"' 2>/dev/null || true
sleep 1
open -a SwiftBar

echo "Installed. SwiftBar plugin folder: $PLUGIN_DIR"
echo "Look for the clock icon and today's total in the menu bar, on the right."
echo "Nothing there? Open SwiftBar's menu → Refresh all."
